In [42]:
class Vektor:
    def __init__(self,element=None,size=None):
        if(element!=None and size!=None):
            self.element=element
            self.size=size
        elif(element!=None):
            self.element=element
            self.size=len(self.element)
        elif(size!=None):
            self.element=[]
            for i in range(size):
                self.element.append(0)
        else:
            print("Please ensure your parameter input and complete one of them")

    def jumlah2Vektor(self, vektor):
        vektorResult=Vektor(None,vektor.size)
        for i in range(self.size):
            vektorResult.element[i]=vektor.element[i]+self.element[i]
        
        vektorResult.size=len(vektorResult.element)
        return vektorResult
    
    def selisih2Vektor(self,vektor):
        vektorResult=Vektor(None,vektor.size)
        for i in range(self.size):
            vektorResult.element[i]=self.element[i]-vektor.element[i]
        
        vektorResult.size=len(vektorResult.element)
        return vektorResult
    
    def tampilVektor(self):
        print(self.element)
        
vektor1=Vektor([1,4,3],len([1,4,3]))
vektor1.tampilVektor()
vektor2=Vektor([1,2,7],len([1,2,7]))
vektor2.tampilVektor()
vektorResultan = vektor1.jumlah2Vektor(vektor2)
print("Jumlah vektor1 dan vektor2 adalah ")
vektorResultan.tampilVektor()
vektorResultan = vektor1.selisih2Vektor(vektor2)
print("Selisih vektor1 dan vektor2 adalah ")
vektorResultan.tampilVektor()

[1, 4, 3]
[1, 2, 7]
Jumlah vektor1 dan vektor2 adalah 
[2, 6, 10]
Selisih vektor1 dan vektor2 adalah 
[0, 2, -4]


In [20]:
class Matriks:
    def __init__(self,element,row,column):
        self.element = element
        self.row = row
        self.column = column
    
    def jumlah2Matriks(self,matriks1, matriks2):
        ResultMatriks = Matriks(matriks1.element,matriks1.row,matriks1.column)
        for i in range(matriks1.row):
            for j in range(matriks1.column):
                ResultMatriks.element[i][j]=matriks1.element[i][j]+matriks2.element[i][j]
        return ResultMatriks
    
    def pengurangan2Matriks(self, matriks1, matriks2):
        ResultMatriks = Matriks(matriks1.element,matriks1.row,matriks1.column)
        for i in range(matriks1.row):
            for j in range(matriks1.column):
                ResultMatriks.element[i][j]=matriks1.element[i][j]-matriks2.element[i][j]
        return ResultMatriks
        
    def tampilArray(self):
        for row in (self.element):
            for column in row:
                print(column ,end=" ")
            print()

Matriks1 = Matriks([[1,2,3], [1,4,5], [5,3,6]],3,3)
print("Matriks 1")
Matriks1.tampilArray()
print()
Matriks2 = Matriks([[5,1,7], [4,0,5], [1,3,9]],3,3)
print("Matriks 2")
Matriks2.tampilArray()
print()

ResultMatriks = Matriks([[0,0,0], [0,0,0], [0,0,0]],3,3)
ResultMatriks = ResultMatriks.jumlah2Matriks(Matriks1,Matriks2)
print("Penjumlahan dua matriks")
ResultMatriks.tampilArray()
print()

Matriks1 = Matriks([[1,2,3], [1,4,5], [5,3,6]],3,3)
print("Matriks 1")
Matriks1.tampilArray()
print()
Matriks2 = Matriks([[5,1,7], [4,0,5], [1,3,9]],3,3)
print("Matriks 2")
Matriks2.tampilArray()
print()

PenguranganMatriks = Matriks([[0,0,0], [0,0,0], [0,0,0]],3,3)
PenguranganMatriks = PenguranganMatriks.pengurangan2Matriks(Matriks1,Matriks2)
print("Pengurangan dua matriks")
PenguranganMatriks.tampilArray()

Matriks 1
1 2 3 
1 4 5 
5 3 6 

Matriks 2
5 1 7 
4 0 5 
1 3 9 

Penjumlahan dua matriks
6 3 10 
5 4 10 
6 6 15 

Matriks 1
1 2 3 
1 4 5 
5 3 6 

Matriks 2
5 1 7 
4 0 5 
1 3 9 

Pengurangan dua matriks
-4 1 -4 
-3 4 0 
4 0 -3 


In [19]:
class Array2DimBedaElemen:
    def __init__(self,element):
        self.element = element
        self.size = len(self.element)
        
    def jumlah2Matriks(self,matriks1, matriks2):
        ResultMatriks = Array2DimBedaElemen(matriks1.element)
        for row in range(len(matriks1.element)):
            for column in range(len(matriks1.element[row])):
                ResultMatriks.element[row][column]=matriks1.element[row][column]+matriks2.element[row][column]
        return ResultMatriks
    
    def pengurangan2Matriks(self,matriks1, matriks2):
        ResultMatriks = Array2DimBedaElemen(matriks1.element)
        for row in range(len(matriks1.element)):
            for column in range(len(matriks1.element[row])):
                ResultMatriks.element[row][column]=matriks1.element[row][column]-matriks2.element[row][column]
        return ResultMatriks
    
    def tampilArray(self):
        for row in (self.element):
            for column in row:
                print(column ,end=" ")
            print()

Matriks1= Array2DimBedaElemen([[1,4,2],[3,2],[5,9,4,6]])
print("Matriks 1")
Matriks1.tampilArray()
Matriks2= Array2DimBedaElemen([[8,1,3],[1,5],[5,7,3,8]])
print("Matriks 2")
Matriks2.tampilArray()
print()
ResultMatriks = Array2DimBedaElemen([[0,0,0], [0,0,0], [0,0,0]])
ResultMatriks = ResultMatriks.jumlah2Matriks(Matriks1,Matriks2)
print("Penjumlahan dua matriks")
ResultMatriks.tampilArray()
print()

Matriks1= Array2DimBedaElemen([[1,4,2],[3,2],[5,9,4,6]])
print("Matriks 1")
Matriks1.tampilArray()
Matriks2= Array2DimBedaElemen([[8,1,3],[1,5],[5,7,3,8]])
print("Matriks 2")
Matriks2.tampilArray()

pengurangan2Matriks = Array2DimBedaElemen([[0,0,0], [0,0,0], [0,0,0]])
pengurangan2Matriks = pengurangan2Matriks.pengurangan2Matriks(Matriks1,Matriks2)
print("Pengurangan dua matriks")
pengurangan2Matriks.tampilArray()
print()

Matriks 1
1 4 2 
3 2 
5 9 4 6 
Matriks 2
8 1 3 
1 5 
5 7 3 8 

Penjumlahan dua matriks
9 5 5 
4 7 
10 16 7 14 

Matriks 1
1 4 2 
3 2 
5 9 4 6 
Matriks 2
8 1 3 
1 5 
5 7 3 8 
Pengurangan dua matriks
-7 3 -1 
2 -3 
0 2 1 -2 



In [41]:
import numpy as np


class Array3DimSama:
    def __init__(self,element):
        self.element = element
        self.size = len(self.element)
    
    def jumlah2Matriks(self,matriks1, matriks2):
        ResultMatriks = Array3DimSama(matriks1.element)
        for row in range(len(matriks1.element)):
            for column in range(len(matriks1.element[row])):
                for dimen in range(len(matriks1.element[row][column])):
                    ResultMatriks.element[row][column][dimen]=matriks1.element[row][column][dimen]+matriks2.element[row][column][dimen]
        return ResultMatriks
    
    def pengurangan2Matriks(self,matriks1, matriks2):
        ResultMatriks = Array3DimSama(matriks1.element)
        for row in range(len(matriks1.element)):
            for column in range(len(matriks1.element[row])):
                for dimen in range(len(matriks1.element[row][column])):
                    ResultMatriks.element[row][column][dimen]=matriks1.element[row][column][dimen]-matriks2.element[row][column][dimen]
        return ResultMatriks
    
    def tampilArray(self):
        print(self.element)
        
        
array  = np.array([[[1,2,7],[1,5,5]],[[1,0,2],[0,3,0]],[[6,2,8],[1,9,4]]])
array1 = np.array([[[1,6,3],[4,2,6]],[[1,2,3],[1,2,3]],[[1,2,3],[1,5,4]]])

Matriks1 = Array3DimSama(array)
print("Matriks 1")
Matriks1.tampilArray()
Matriks2 = Array3DimSama(array1)
print("Matriks 2")
Matriks2.tampilArray()
print()

ResultMatriks = Array3DimSama(np.array([[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]]))
ResultMatriks = ResultMatriks.jumlah2Matriks(Matriks1,Matriks2)
print("Penjumlahan dua matriks")
ResultMatriks.tampilArray()
print()

array  = np.array([[[1,2,7],[1,5,5]],[[1,0,2],[0,3,0]],[[6,2,8],[1,9,4]]])
array1 = np.array([[[1,6,3],[4,2,6]],[[1,2,3],[1,2,3]],[[1,2,3],[1,5,4]]])
Matriks1 = Array3DimSama(array)
print("Matriks 1")
Matriks1.tampilArray()
Matriks2 = Array3DimSama(array1)
print("Matriks 2")
Matriks2.tampilArray()
print()

pengurangan2Matriks = Array3DimSama(np.array([[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]]))
pengurangan2Matriks = pengurangan2Matriks.pengurangan2Matriks(Matriks1,Matriks2)
print("Pengurangan dua matriks")
pengurangan2Matriks.tampilArray()
            

Matriks 1
[[[1 2 7]
  [1 5 5]]

 [[1 0 2]
  [0 3 0]]

 [[6 2 8]
  [1 9 4]]]
Matriks 2
[[[1 6 3]
  [4 2 6]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 5 4]]]

Penjumlahan dua matriks
[[[ 2  8 10]
  [ 5  7 11]]

 [[ 2  2  5]
  [ 1  5  3]]

 [[ 7  4 11]
  [ 2 14  8]]]

Matriks 1
[[[1 2 7]
  [1 5 5]]

 [[1 0 2]
  [0 3 0]]

 [[6 2 8]
  [1 9 4]]]
Matriks 2
[[[1 6 3]
  [4 2 6]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 5 4]]]

Pengurangan dua matriks
[[[ 0 -4  4]
  [-3  3 -1]]

 [[ 0 -2 -1]
  [-1  1 -3]]

 [[ 5  0  5]
  [ 0  4  0]]]
